@startuml

title __APP's Class Diagram__\n

  namespace com.bumptech.glide {
    class com.bumptech.glide.GeneratedAppGlideModuleImpl {
    }
  }
  

  namespace com.bumptech.glide {
    class com.bumptech.glide.GeneratedRequestManagerFactory {
    }
  }
  

  namespace com.example.tiktok {
    interface com.example.tiktok.ApiService {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.BuildConfig {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.GlideApp {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.GlideOptions {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.GlideRequest {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.GlideRequests {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.MainActivity {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.MyAdapter {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.MyAppGlideModule {
    }
  }
  

  namespace com.example.tiktok {
    class com.example.tiktok.VideoItem {
    }
  }
  

  com.bumptech.glide.GeneratedAppGlideModuleImpl -up-|> com.bumptech.glide.GeneratedAppGlideModule
  com.bumptech.glide.GeneratedAppGlideModuleImpl o-- com.example.tiktok.MyAppGlideModule : appGlideModule
  com.bumptech.glide.GeneratedRequestManagerFactory .up.|> com.bumptech.glide.manager.RequestManagerRetriever.RequestManagerFactory
  com.example.tiktok.GlideOptions .up.|> java.lang.Cloneable
  com.example.tiktok.GlideOptions -up-|> com.bumptech.glide.request.RequestOptions
  com.example.tiktok.GlideRequest .up.|> java.lang.Cloneable
  com.example.tiktok.GlideRequest -up-|> com.bumptech.glide.RequestBuilder
  com.example.tiktok.GlideRequests -up-|> com.bumptech.glide.RequestManager
  com.example.tiktok.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.tiktok.MainActivity o-- com.example.tiktok.MyAdapter : mAdapter
  com.example.tiktok.MyAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.tiktok.MyAppGlideModule -up-|> com.bumptech.glide.module.AppGlideModule


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
